packages:
  - apps/*
  - config/*
  - packages/*
  - harness

catalog:
  zod: 3.23.8

catalogs:
  ai: 
    "ai": "^5.0.15"
    "@openrouter/ai-sdk-provider": "^1.1.2"
    
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0

  stack:
    "@types/node": 22.8.6
    "hono": 4.9.2
    "zod":  4.0.17