import fs from "fs"

export const writeConfig = async () => {
  const contracts = await listContracts(process.cwd() + "/contracts")

  return fs.writeFileSync(
    process.cwd() + "/.hybrid/index.ts",
    `
// This file is auto-generated by the Hybrid CLI

export const Contracts = {
  ${contracts
    .map((c) => {
      const name = c.replace(".sol", "")
      return `${name}: {
    abi: require("./out/${name}.sol/${name}.json").abi,
    bytecode: require("./out/${name}.sol/${name}.json").bytecode.object,
  }`
    })
    .join(",\n  ")}
};`
  )
}

const listContracts = async (dir) => {
  const files = await fs.readdirSync(dir)
  return files.filter((f) => !f.match(/(t|test)\.sol$/))
}
