name: Run Agent Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: 
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb

jobs:
  agent-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # important for git diff to work correctly

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.5
          run_install: false
      
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      
      - run: pnpm install
      
      - name: Check API Key Status
        run: |
          if [ -z "$OPENROUTER_API_KEY" ]; then
            echo "⚠️ OPENROUTER_API_KEY is not set - agent tests will be skipped"
          elif [ ${#OPENROUTER_API_KEY} -lt 10 ]; then
            echo "⚠️ OPENROUTER_API_KEY appears invalid (too short) - agent tests will be skipped"
          else
            echo "✅ OPENROUTER_API_KEY is set and appears valid"
          fi
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      
      - name: Run Agent Tests on changed files
        timeout-minutes: 10
        run: |
          # Set the base reference based on event type
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
          else
            BASE_REF="${{ github.event.before }}"
          fi
          
          # Get changed files related to agents, tools, or AI functionality
          git diff --name-only $BASE_REF HEAD | grep -E '^(apps/app/src/agents/|apps/app/src/tools/|packages/)' > changed.txt || true
          
          if [ -s changed.txt ]; then
            echo "Found changes in agent-related files:"
            cat changed.txt
            
            # Run tests for changed agent files with timeout
            if git diff --name-only $BASE_REF HEAD | grep -q '^apps/app/src/agents/'; then
              echo "Running agent tests..."
              timeout 8m pnpm --filter app test:agents || {
                echo "Agent tests timed out or failed"
                exit 1
              }
            fi
            
            # Run tests for changed tool files with timeout
            if git diff --name-only $BASE_REF HEAD | grep -q '^apps/app/src/tools/'; then
              echo "Running tool tests..."
              timeout 5m pnpm --filter app test:tools || {
                echo "Tool tests timed out or failed"
                exit 1
              }
            fi
            

          else
            echo "No relevant agent/tool file changes. Skipping tests."
          fi
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
