name: Test XMTP Package

on:
  push:
    branches: [main]
    paths:
      - 'packages/xmtp/**'
      - '.github/workflows/test-xmtp.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/xmtp/**'
      - '.github/workflows/test-xmtp.yml'

jobs:
  test-xmtp:
    name: Test XMTP Package
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.5

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dependencies
        run: pnpm build

      - name: Run XMTP package tests
        run: |
          cd packages/xmtp
          pnpm test

